### PR TITLE
Align generated code output for tests

### LINKED ISSUE #47: Invalid import in simplegrpc test
There's a discrepancy between the checked in code in `codegen/tests/simplegrpc/simplesg/grpc_interface.go` and the generated code that's causing a compilation error in the tests.

Checked in code:
```go
import (
    "github.com/anz-bank/sysl-go/codegen/tests/simple"
)
```

Generated code:
```go
import (
    "github.com/anz-bank/sysl-go/codegen/tests/simplegrpc/simple"
)
```

### PR DESCRIPTION
**Pull request by gkanz**
All output is now written to `codegen/tests/<sysl package>`.
Simplifies make by giving all generated output a common base.

Test cases can reuse generated code from other test cases. For example,
a gRPC server  calling a rest endpoint.

The hand-crafted callback can also be reused across tests.

Fixes #47

### CODE REVIEW

**Review by andrewemeryanz — COMMENTED** [review]
I'm seeing a couple of missing imports for tests:

* `codegen/tests/simple/serviceinterface.go` is missing `github.com/anz-bank/sysl-go/config`
* `codegen/tests/simplegrpc/grpc_handler.go` is missing `github.com/anz-bank/sysl-go/codegen/tests/simple`

Found by running `make clean && make gen`.

**Comment by gkanz** [comment]
> seeing a couple of missing imports for test

My environment must be fixing those automatically... I assume it must be `goimports`. I'll see if `gofmt` will make it compilable without import automagic.

**Comment by gkanz** [comment]
> * `codegen/tests/simplegrpc/grpc_handler.go` is missing `github.com/anz-bank/sysl-go/codegen/tests/simple`

I replaced `goimports` with `gofmt` in `Makefile` and I can see that this one is definitely there... what happens if you do the same?

**Review by andrewemeryanz — APPROVED** [review]
Looks good.

**Pull request merged**
