### PR TITLE
Support XML and PDF in SendHTTPResponse

### PR DESCRIPTION
**Pull request by jecofang01**
As needed for dcx/bff

### CODE REVIEW

**Comment by springwiz** [comment]
@jecofang01 There was a similar to change I had done before to skip json encoding for xml content type in request and response while talking to downstream. All you need to do is to the set the content-type header in the context. Can you please let me know, how is your change different from that? Please refer to the test case func TestSendHTTPResponseXMLBody(t *testing.T) { in the rest lib. I can't add a reference to that PR as it was in the Server-lib repo.

**Comment by jecofang01** [comment]
hi @springwiz , this change is for upstream. The generated code send out the response to upstream by calling `SendHTTPResponse`.

**Review by springwiz — DISMISSED** [review]
Can you please show how the changes look like in the Sysl file. Please make the changes in the simple.sysl, generate go code and add the test cases to simple_test.go.

**Comment by jecofang01** [comment]
@springwiz Thanks for your comments. I'm trying to add the test cases, however I was blocked by https://github.com/anz-bank/sysl/issues/725. I will update once the issue fixed.

**Review by ghost — APPROVED** [review]

**Pull request merged**
