### PR TITLE
Allow endpoints to return sequences, Fix build.

### LINKED ISSUE #76: Return sequence of Downstream.Abc creates wrong Go code
Downstream is a third party API imported in the current Sysl file.

```
/abc
    GET:
        return ok <: sequence of Downstream.Aaa
```

In serviceinterface.go, it creates go code below.

```
GetAbcList func(ctx context.Context, req *GetAbcListRequest, client GetAbcListClient) (*[]DownstreamAaa, error)
```

Expect:

```
GetAbcList func(ctx context.Context, req *GetAbcListRequest, client GetAbcListClient) (*[]downstream.Aaa, error)
```

FYI The following Sysl code correctly creates go code.

```
return ok <: sequence of Bbb.  # Bbb is defined in the same file
return ok <: Downstream.Aaa
```

Relocated from: https://github.com/anz-bank/gosysl/issues/10

### PR DESCRIPTION
**Pull request by springwiz**
Fixes codegen to correctly generate code when the endpoints return sequences.

Closes: #76 and #74

### CODE REVIEW

**Review by andrewemeryanz — CHANGES_REQUESTED** [review]
Code change looks good. Can you put some more detail in the commit message and link it to the issue please: `Closes: #76`.

This pull request addresses two issues. In future, please consider splitting these into separate commits (or separate pull requests) to make reviewing easier.

**Comment by andrewemeryanz** [comment]
> Allow endpoints to return sequences
> 
> Fixes codegen to correctly generate code when the endpoints 
> return sequences.
>
> Closes: #76 and #74

Can you put this information in the commit message please:
```
git commit --amend
```

**Comment by springwiz** [comment]
> > Allow endpoints to return sequences
> > Fixes codegen to correctly generate code when the endpoints
> > return sequences.
> > Closes: #76 and #74
> 
> Can you put this information in the commit message please:
> 
> ```
> git commit --amend
> ```

Done. The comments on the PR are automatically recorded on the master though when you do squash and merge.

**Review by andrewemeryanz — APPROVED** [review]
Good.

**Pull request merged**
