### PR TITLE
Reimplement codegen in arr.ai

### PR DESCRIPTION
**Pull request by anzdaddy**
Test with `./test-arrai`. It will build the following tests: deps, dbendpoints, downstream, simple, simplegrpc. It will then diff the output against the output generated by the current version of the code generator.

The other scenarios in testdata aren't yet tested because setting them in the build system was more fiddly. This is pending work.

### CODE REVIEW

**Review by gkanz — COMMENTED** [review]
Amazing, much more readable than the Sysl version.

To run `./test-arrai`:
- Required `brew install colordiff`. :-)
- Required `rm -r codegen/arrai/tests/*` before anything would happen as makefile tests presence of dirs (they are in the git repo so "nothing to be done").

**Comment by ghost** [comment]
@gkanz 
> Amazing, much more readable than the Sysl version

Absolutely! with very minimal effort I have been able to fix issues and add new files in a matter of hours. Very happy to switch dcx/bff to this!

**Review by ghost — APPROVED** [review]
Very cool

**Comment by anzdaddy** [comment]
>     * Required `brew install colordiff`. :-)
>     * Required `rm -r codegen/arrai/tests/*` before anything would happen as makefile tests presence of dirs (they are in the git repo so "nothing to be done").

Good points, however test-arrai is just an interim tool for my own use until I pull the pin on the Sysl transforms.

**Pull request merged**
